### ISSUE TITLE
Store CSV metadata in yaml (or similar) format

### ISSUE THREAD

**Issue by ashiklom** [FoRTExperiment/fortedata#5]
Definitely not a priority, but this could be a cool way to add detailed metadata and constraints/sanity checks for our data. For example, given that the current `fd_plots.csv` looks like this:

```csv
Replicate,Plot,Longitude,Latitude,Disturbance_severity
A,1,-100,47,0
A,2,-100,47,45
# ...
```

...we could have an accompanying YAML metadata file that looks like this:

```yml
title: FoRTE plots
description: Plot IDs, and other information, about plots
columns:
  - name: Replicate
    description: "Group of disturbance treatments"
    class: factor
    levels: [A, B, C, D]
  - name: Plot
    description: "Individual disturbance treatment within a replicate"
    class: integer
    constraints:
      - "all(x > 0)"
  - name: Longitude
    description: "Site longitude"
    class: numeric
    constraints:
      - "all(x > 40)"
      - "all(x < 50)"
  # etc...
```

YAML has the advantage that it is both human- and machine-readable, widely used, and largely language-agnostic (which would make it easier to share our data with, say, Python users). Also, the R `yaml` package has the nice property of having no dependencies of its own.

A few thoughts about implementation:
- The value of `class` for each column can be passed to the `colClasses` argument of `read.table`. This also has the nice side-effect of increasing speed (of the CSV read itself; for smaller files, reading the YAML first probably imposes a tiny speed penalty).
- `constraints` can be converted to R functions via `eval(parse(text = z))`, where `z` is `paste0("function (x) {", constraint, "}")` (there are a few [additional things](https://gist.github.com/ashiklom/5e427b6a14e346fcbca71a0a63fc1c02) that can be done to make this more secure). Then, those functions can be applied to the data in a loop or apply-like statement.
- In the past, I've [experimented](https://github.com/ashiklom/metar) with storing metadata as attributes in the resulting table. This is made much more robust via the recent [`vctrs` package](https://vctrs.r-lib.org/). However, everything about this introduces a lot of complexity for (arguably) relatively little gain. It's probably better to just add an optional argument like `info = TRUE` to all the loading functions that causes these metadata to be pretty-printed when the data are loaded, and/or a function like `fd_describe("fd_plots")` that does this on demand.
  - One possible exception to this is values with units. I think there could be some value to leveraging something like the [`units` package](https://r-quantities.github.io/units/), which (among other things) automatically does unit conversions for certain operations and prevents incompatible operations from happening. At the very least, it may be worth adding an optional `units` argument (`FALSE` by default) that, if `TRUE`, also parses unit information.
